### ISSUE TITLE
Error raised in getValue function if click occurs while a table is changing

### ISSUE THREAD

**Issue by duffyjp** [tofsjonas/sortable#49]
I have a table that can be many thousands of rows long, so I load 100 in the initial page load and then use `fetch` to append more rows 1000 at a time.

I'm running into a situation where if a column is clicked while data is still loading getValue throws an error and the table doesn't sort.  

```
TypeError: Cannot read properties of undefined (reading 'dataset')
    at getValue (sortable-27aa9e4755817a61c6c3ea3b85a095c3066bd56a8b951be2714ae9532957a6f8.js:61:80)
    at compare_1 (sortable-27aa9e4755817a61c6c3ea3b85a095c3066bd56a8b951be2714ae9532957a6f8.js:93:25)
    at sortable-27aa9e4755817a61c6c3ea3b85a095c3066bd56a8b951be2714ae9532957a6f8.js:106:32
    at Array.sort (<anonymous>)
    at HTMLDocument.<anonymous> (sortable-27aa9e4755817a61c6c3ea3b85a095c3066bd56a8b951be2714ae9532957a6f8.js:105:22)
```

As a mitigation I wrapped the code in a try/catch: and just return an empty string.  

```javascript
function getValue(element) {
    try {
        return (alt_sort_1 && element.dataset.sortAlt) || element.dataset.sort || element.textContent;
    }
    catch (error) {
        return '';
    }
}
```

In a perfect world once a column is sorted I'd love to be able to detect changes to the table and resort it so the appended data isn't just slapped at the bottom of the table.  Maybe something like the click() click() from https://github.com/tofsjonas/sortable/issues/32 ?

I suppose a partially loaded table not sorting isn't a terrible behavior, but the CSS classes do change as that happens first so it definitely feels broken.

**Comment by tofsjonas** [comment]
To be able to handle sorting a "broken" table, or a table in transition, well, I would say that that is outside the scope of sortable.. 🤔️

(I looked at sorting the table after adding or removing rows, but I did not like solution 😬️ )

Plus, it's kind of unnecessary, since you're the one adding new data. Here's what I would do:

- Show a spinner, block sorting 
- Add more stuff to the table
- Sort, with something like resortTable() from #32
- Remove spinner and re-enable sorting.

I think that would be the best solution, both from a dev and ux perspective 🥳️
